language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --no-interaction
  - composer info -i

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
